---
- name: install docker on redhat
  hosts: redhat

  tasks:
  - name: add docker-ce-stable repo
    yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
      file: docker-ce
      enabled: true
    become: true

  - name: add docker-ce-stable-debuginfo  repo
    yum_repository:
      name: docker-ce-stable-debuginfo
      description: Docker CE Stable - Debuginfo $basearch
      baseurl: https://download.docker.com/linux/centos/$releasever/debug-$basearch/stable
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
      file: docker-ce
      enabled: false
    become: true

  - name: remove old docker packages
    dnf:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker 
      - docker-engine
      - docker-ce-cli
      - docker-ce

  - name: install needed dependencies
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - lvm2
      - device-mapper
      - device-mapper-persistent-data
      - device-mapper-event
      - device-mapper-libs
      - device-mapper-event-libs

  - name: install docker-ce
    command: dnf -y install docker-ce --nobest

  - name: check is docker service is running
    systemd:
      name: docker
      state: started

