version: '2'

services:
  jenkins:
    volumes:
     - /data/jenkins/ext_config/jenkins_plugins.txt:/var/jenkins_home/jenkins_plugins.txt
     - /data/jenkins/ext_config/casc.yml:/var/jenkins_home/casc.yml
     - jenkins_data:/var/jenkins_home
     - /data/jenkins/ext_config/id_rsa:/var/jenkins_home/.ssh/id_rsa
     - /data/jenkins/ext_config/gerrit-trigger.xml:/var/jenkins_home/gerrit-trigger.xml:rw
    container_name: jenkins
    image: jenkins/jenkins
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yml
    command: sh -c "/usr/local/bin/install-plugins.sh < /var/jenkins_home/jenkins_plugins.txt;    
                    /sbin/tini -- /usr/local/bin/jenkins.sh"
    ports:
       - "50000:50000"
       - "92:8080"

volumes:
  jenkins_data:
    external: true