#- name: check if nagios exists
#  command: systemctl status nagios
#  register: check_nagios
#  ignore_errors: True
  
- name: Setup jenkins and gerrit
  include: "{{ ansible_pkg_mgr }}.yml"
  #when: "check_nagios.rc != 0"