- name: Delete file for fixing bad proxy
  file:
    name: /var/lib/apt/lists/
    state: absent

- name: Create folder /var/lib/apt/lists/  for fixing bad proxy
  file:
    name: /var/lib/apt/lists/
    state: directory
  
- name: Create file /etc/apt/apt.conf.d/99fixbadproxy and folder  for fixing bad proxy
  file:
    name: /etc/apt/apt.conf.d/99fixbadproxy
    state: touch

- name: Fix bad proxy for apt packges
  lineinfile:
    path: /etc/apt/apt.conf.d/99fixbadproxy
    line: "{{ item }}"
    create: yes
  loop:
    - Acquire::http::Pipeline-Depth 0;
    - Acquire::http::No-Cache true;
    - Acquire::BrokenProxy true;
  
- name: Apt clean
  apt:
    autoclean: yes

- name: Apt update with dpkg options
  apt:
    update_cache: yes
    dpkg_options: "Acquire::CompressionTypes::Order::=gz"

- name: Install libgd-dev, python-passlib
  apt:
    allow_unauthenticated: yes
    update_cache: yes
    name: "{{ item }}"
    state: present
    install_recommends: yes
  loop:
    - php-gd
    - libgd-dev
    - python3-passlib
    - python-passlib
    - php
    - apache2
    - apache2-utils
    - php
    - gcc
    - glibc-source
    - snmp
    - unzip
    - tar
    - curl
    - fcgiwrap

- name: Install Nagios from makefile
  include_tasks: common.yml  

- name: Enable the Apache2 module cgi
  apache2_module:
    state: present
    name: cgi

- name: Restart apache2
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2

- name: Check nagios config
  command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
  register: check_nagios
  ignore_errors: True

- name: Start nagios service
  systemd:
    state: started
    daemon_reload: yes
    name: nagios
  when: "check_nagios.rc == 0"