- name: Install libgd-dev, python-passlib
  apt:
    allow_unauthenticated: yes
    update_cache: yes
    name: "{{ item }}"
    state: present
    install_recommends: yes
  loop:
    - php-gd
    - libgd-dev
    - python3-passlib
    - python-passlib
    - php
    - apache2
    - apache2-utils
    - php
    - gcc
    - glibc-source
    - snmp
    - unzip
    - tar
    - curl
    - fcgiwrap
    - sudo

- name: Install Nagios from makefile
  include_tasks: common.yml  

- name: Enable the Apache2 module cgi
  apache2_module:
    state: present
    name: cgi

- name: Restart apache2
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2

- name: Check nagios config
  command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
  register: check_nagios
  ignore_errors: True

- name: Start nagios service
  systemd:
    state: started
    daemon_reload: yes
    name: nagios
  when: "check_nagios.rc == 0"

- name: Add nagios agents to nagios server
  include_tasks: add_nrpe_host.yml