- name: Install Required Dependencies dnf
  dnf:
    state: present
    name: "{{ item }}"
  loop:
    - httpd
    - httpd-tools
    - php
    - gcc
    - glibc-common
    - gd
    - gd-devel
    - make
    - net-snmp
    - unzip
    - tar
    - curl

- name: Install nagios from makefile
  include_tasks: common.yml

- name: Stop firewalld
  systemd: 
    state: stopped
    name: firewalld

- name:  Add nagios to firewalld rules  
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled

- name: Start firewalld
  systemd:
    state: started
    name: firewalld

- name: Update packages
  dnf:
    name: httpd
    update_cache: yes
    state: present

- name: Restart httpd server
  systemd:
    name: httpd
    enabled: yes
    state: restarted

- name: Check nagios config
  command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
  register: check_nagios
  ignore_errors: True

- name: Start nagios service
  systemd:
    state: started
    daemon_reload: yes
    name: nagios
  when: "check_nagios.rc == 0"