  - name: import yum repos ditionary
    include_vars : yum_repos.yml
   
  - name: add "{{ item.name }}" repository
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}" 
      baseurl: "{{ item.baseurl }}"
      gpgcheck: "{{ item.gpgcheck }}"
      gpgkey: "{{ item.gpgkey }}"
      file: "{{ item.file }}"
      enabled: "{{ item.enabled }}"
    become: true
    loop: "{{ repos }}"

  - name: remove old docker packages
    dnf:
      name: "{{ item }}"
      state: absent
    loop:
      - docker 
      - docker-engine
      - docker-ce-cli
      - docker-ce

  - name: install needed dependencies
    dnf:
      name: "{{ item }}" 
      state: present
    loop:
      - lvm2
      - device-mapper
      - device-mapper-persistent-data
      - device-mapper-event
      - device-mapper-libs
      - device-mapper-event-libs
  
  - name: install docker-ce
    command: dnf -y install docker-ce --nobest
    notify: run_docker_systemd

