  - name: import yum repos ditionary
    include_vars : yum_repos.yml
   
  - name: add "{{ item.name }}" repository
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}" 
      baseurl: "{{ item.baseurl }}"
      gpgcheck: "{{ item.gpgcheck }}"
      gpgkey: "{{ item.gpgkey }}"
      file: "{{ item.file }}"
      enabled: "{{ item.enabled }}"
    become: true
    loop: "{{ repos }}"

  - name: yum clean
    shell: yum clean all

  - name: subscription-manager refresh
    shell: subscription-manager refresh
    when: ansible_distribution == 'RedHat'

  - name: yum clean
    shell: yum update -y

  - name: install needed dependencies
    dnf:
      name: "{{ item }}" 
      state: present
      validate_certs: no
    loop:
      - lvm2
      - device-mapper
      - device-mapper-persistent-data
      - device-mapper-event
      - device-mapper-libs
      - device-mapper-event-libs
  
  - name: install docker-ce
    command: dnf -y install docker-ce --nobest
    notify: run_docker_systemd

