  - name: remove old docker packages
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-engine
      - docker.io
      - containerd 
      - runc

  - name: update apt
    apt:
      update_cache: yes

  - name: install packages needed for docker
    apt:
      name: "{{ item }}"
      state:  present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an Apt signing key
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: get lsb-release
    command: lsb_release -cs
    register: result

  - name: add repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ result.stdout }} stable
      state: present
      
  - name: install docker packages 
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Make sure a service is running
    systemd:
      state: started
      name: docker