- name: Install needed apk packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - nagios-plugins-all
    - grep

- name: 
  file:
    path: /usr/local/nagios/
    state: directory

- name: Create a symbolic link nagios plugins
  file:
    dest: /usr/local/nagios/libexec
    src: /usr/lib/nagios/plugins
    state: link