- name: Yum clean
  shell: yum clean all

- name: Subscription-manager refresh
  shell: subscription-manager refresh
  when: ansible_distribution == 'RedHat'
  
- name: Yum update
  shell: yum update -y

- name: Change https to http in repos.d
  shell: sed -i 's/https/http/g' /etc/yum.repos.d/* ; yum update -y
  when: ansible_distribution == 'CentOS'

- name: Add epel repo for centos 8
  dnf: 
    state: present
    name: "{{ item }}"
    disable_gpg_check: yes
  loop: 
    - epel-release
  when: ansible_distribution == 'CentOS'

- name: install federa repos
  shell: yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y

- name: change https to http in repos.d
  shell: sed -i 's/https/http/g' /etc/yum.repos.d/*
  when: ansible_distribution == 'CentOS'

- name: Install packages
  dnf: 
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - make
    - curl
    - tar
    - gcc
    - grep
    - check_nrpe
  
- name: Install nagios plugins from makefile
  include_tasks: common.yml

- name: Check if firewalld is enabled
  command: systemctl status firewalld 
  register: check_firewalld
  ignore_errors: True

- name: Stop firewalld
  systemd: 
    state: stopped
    name: firewalld
  when: "check_firewalld.rc != 0"
  ignore_errors: True


- name: Add nrpe to firewalll rules
  firewalld:
    service: nrpe
    permanent: yes
    state: enabled
    zone: public
  when: "check_firewalld.rc != 0"
  ignore_errors: True


- name: Start firewalld
  systemd:
    state: started
    name: firewalld
  when: "check_firewalld.rc != 0"
  ignore_errors: True


- name: Create a symbolic link to check_nrpe
  file:
    src: /usr/lib64/nagios/plugins/check_nrpe
    dest: /usr/local/nagios/libexec/check_nrpe
    state: link