- name: Yum clean
  shell: yum clean all

- name: Subscription-manager refresh
  shell: subscription-manager refresh
  when: ansible_distribution == 'RedHat'
  
- name: Yum update
  shell: yum update -y

- name: Change https to http in repos.d
  shell: sed -i 's/https/http/g' /etc/yum.repos.d/* ; yum update -y
  when: ansible_distribution == 'CentOS'

- name: Add epel repo for centos 8
  dnf: 
    state: present
    name: "{{ item }}"
    disable_gpg_check: yes
  loop: 
    - epel-release
  when: ansible_distribution == 'CentOS'

- name: install federa repos
  shell: yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y

- name: change https to http in repos.d
  shell: sed -i 's/https/http/g' /etc/yum.repos.d/*
  when: ansible_distribution == 'CentOS'

- name: Install packages
  dnf: 
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - make
    - curl
    - tar
    - gcc
  
- name: Install nagios plugins from makefile
  include_tasks: common.yml