- name: check if nagios plugins exists
  command: ls /usr/local/nagios/libexec
  register: check_nagios
  ignore_errors: True
  
- name: Install nagios plugins
  include: "{{ ansible_pkg_mgr }}.yml"
  when: "check_nagios.rc != 0"
